mybatis:
  type-aliases-package: com.qf.entity
  mapper-locations: classpath:com/qf/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/car?serverTimezone=Asia/Shanghai
    username: root
    #这里密码应该加上单引号
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html